#! /bin/bash

export TAG_NAME="monte-carlo-fsharp"

function build-docker() {
    docker build -f Dockerfile -t $TAG_NAME . $@
}

function dock() {
    docker run --rm -it $TAG_NAME $@
}

function repl() {
    dock fsharpi
}

function execute() {
    dock fsharpi $@
}

echo "$@"

$@
