#! /bin/bash

export TAG_NAME="monte-carlo-fsharp"

function build-docker() {
    docker build -f Dockerfile -t $TAG_NAME . $@
}

function repl() {
    build-docker >/dev/null
    docker run --rm -it $TAG_NAME $@
}

function execute() {
    build-docker >/dev/null
    docker run --rm -it $TAG_NAME fsharpi $1
}

echo "$@"

$@
