#! /bin/bash

export TAG_NAME="monte-carlo-clojure"
export IP=$(ifconfig en0 | grep inet | awk '$1=="inet" {print $2}')

function build-docker() {
    docker build -f Dockerfile -t $TAG_NAME . $@
}

function dock() {
    docker run \
        -e DISPLAY=$IP:0 \
        -v /tmp/.X11-unix:/tmp/.X11-unix \
        -v $HOME/.Xauthority:/root/.Xauthority --net=host \
        -v $PWD:"/root/simulation_methods" \
        -w "/root/simulation_methods" \
        --rm -it $TAG_NAME $@
}

function repl() {
    dock lein repl
}

echo "$@"

$@
