#! /bin/bash

export TAG_NAME="monte-carlo-clojure"

function build-docker() {
    docker build -f Dockerfile -t $TAG_NAME . $@
}

function dock() {
    docker run \
        -e DISPLAY=$IP:0 \
        -v /tmp/.X11-unix:/tmp/.X11-unix \
        -v $HOME/.Xauthority:/root/.Xauthority --net=host \
        --rm -it $TAG_NAME $@
}

function repl() {
    dock lein repl
}

echo "$@"

$@
